### ISSUE TITLE
replace httpd control with osc

### ISSUE THREAD

**Issue by dasantonym** [denjello/pi-DJex#6]
this removes httpd and php dependency. the script should persist the last set value on change but i'd rather reduce the incoming control to an osc message receiver (less stuff running on the pi).

this could also apply to an option to enable and disable the service or to turn debugging on and off

someone could use a tool like http://archive.cnmat.berkeley.edu/OpenSoundControl/clients/sendOSC.html to make changes to the current settings

**Comment by denjello** [comment]
i think that will make it more stable.

**Comment by dasantonym** [comment]
no longer needed
